---
- name: Install docker pip package
  pip:
    name: docker

- name: Create directory for app
  file:
    path: /opt/vuln-app
    state: directory
    mode: '0777'

- name: Put docker-compose
  template:
    src: "docker-compose.yml.j2"
    dest: "/opt/vuln-app/docker-compose.yml"
  notify: Restart app systemd unit

- name: Update systemd unit
  template:
    src: "systemd.j2"
    dest: "/etc/systemd/system/app.service"
  notify: Restart app systemd unit

- name: Update nginx config
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/conf.d/app.conf"
  notify: Test nginx config

- name: Start and enable the service
  systemd:
    name: 'app'
    state: started
    enabled: true
